### ISSUE TITLE
Singleton version

### ISSUE THREAD

**Issue by JoshuaNovak919** [Yonaba/30log#15]
Is there a way to use this as a singelton? Basically I want an to be able to do something like this:

```
myClass = require( "my_class.lua" ) -- Should call init
myClass:loadStuff()
```

**Comment by Yonaba** [comment]
Hi @JoshuaNovak919 ,

First of all, sorry for the delay.
Well, I am not familiar with the Singleton pattern. I made a bit of digging, and it actually looks like it is fairly simple to implement that feature.
However, I won't include it itself in the library. But, you can, of course, add this to your code and reuse of as you wish.
I am assuming a SingletonClass is a class which has a unique and private instance of itself, and cannot create other instances. Also, this class cannot be subclassed.

This seems to solve the problem. Save it in a file named `singleton.lua` (for example), and call it with require.

```lua
local class = require '30log'
local SingletonClass = class("Singleton")
local instance = SingletonClass()

function SingletonClass.new() 
  error('Cannot instantiate from a Singleton class') 
end

function SingletonClass.init() end

function SingletonClass.extend() 
  error('Cannot extend from a Singleton class')
end

function SingletonClass:getInstance()
  return instance
end

return SingletonClass
````

Though, I cannot really see how you could not achieve the what you wanted to do with a normal class. Hope this helps anyway.
