### ISSUE TITLE
Need help on using new()

### ISSUE THREAD

**Issue by mondwan** [Yonaba/30log#17]
Hello, I get errors as below while calling new()

```/usr/local/share/lua/5.1/30log.lua:12: new() should be called from a class.```

This error source from [here](https://github.com/Yonaba/30log/blob/30log-0.9.1-1/30logclean.lua#L32).

How can I bypass this error?

Since I am using factory pattern like following

```
-- Where moduleName is an object created by 30log
function factory:createCommandUnit(moduleName):
   return require(moduleName)
end

-- Calling in main()
cmd = factory:createCommandUnit('command_date')
cmdInstance = cmd:new() -- get errors here
```

Although there is a new version available, there are so much changed which breaks my original codes.

**Comment by Yonaba** [comment]
Hi, @mondwan,

First of all, thanks using *30log*.

I cannot say much from the code you shared, as I believe the problem is located inside the module "command-date". Anyway, the error you are getting is related to the fact you are calling `new()` from an instance of a class, and __not from the class itself__.

Here is an example to reproduce the error.
Let us consider a class `aClass` and an instance from this class named `anInstanceOfClass`.

```lua
local class = require "30log"
local aClass = class()
local anInstanceOfClass = aClass:new()

-- Let us try to create another instance by calling new from anInstanceOfClass
local anotherInstance = anInstanceOfClass:new() -- error here
````
I would suggest to inspect the code behind the module 'command_date', I believe it returns a call to some new method of a class from an instance.

**Comment by mondwan** [comment]
Ah...  below are codes for ```command_date``` which inherits from ```command_unit``` and inherits from ```command```

# command_unit.lua
```
local commandUnit = command:extends({
    -- _id = 'fooCommandUnit',                                                                                                   
    name = 'fooCommandUnit',
    _author = 'Mond Wan',
})
commandUnit.__name = 'CommandUnit'

return commandUnit  
```

# command_date.lua
```
local CommandDate = commandUnit:extends({
    name = 'CommandDate',
    _author = 'Mond Wan',
    _version = 1,
})
CommandDate.__name = 'CommandDate'

function CommandDate:__init(opt)
....
end

function ....

return CommandDate
```

# command.lua
```
local oop = require '30log'
local command = oop({...})
return command
```

I bet problem comes from ```extends()```. However, I am able to do following object creation.
```
local c = require 'cli_mod.command_date'
local myCommand = c:new() -- no errors
```

Errors only come from the dynamic require calls.
```
-- Where moduleName is an object created by 30log
function factory:createCommandUnit(moduleName):
   return require(moduleName)
end

-- Calling in main()
cmd = factory:createCommandUnit('command_date')
cmdInstance = cmd:new() -- get errors here
```

**Comment by Yonaba** [comment]
I tried for myself, and I didn't get any error.
Since your classes are defined as locals (not globals) in different files (command.lua, command_unit.lua and command_date.lua), how to you extend those classes ? 
I just turned your code this way (side note, I used 30log 1.0.0) syntax.

### `command.lua`
```lua
local oop = require '30log'
local command = oop({...})
return command
````

### `command_unit.lua`
```lua
local command = require 'command'
local commandUnit = command:extend('fooCommandUnit',{
    -- _id = 'fooCommandUnit',                                                                                                   
    _author = 'Mond Wan',
})
return commandUnit 
````
### `command_date.lua`
```lua
local commandUnit = require 'command_unit'
local CommandDate = commandUnit:extend('CommandDate',{
    _author = 'Mond Wan',
    _version = 1,
})
function CommandDate:init(opt) end
return CommandDate
````

### `main.lua`
```lua
local factory = {}

-- Where moduleName is an object created by 30log
function factory:createCommandUnit(moduleName)
   return require(moduleName)
end

-- Calling in main()
cmd = factory:createCommandUnit('command_date')
cmdInstance = cmd:new() -- get errors here
print(cmdInstance) -- instance of 'CommandDate' (table: 0x00030460)
````
Seems fine, to me.

**Comment by mondwan** [comment]
are you using ```30log-0.9.1-1``` for testing?

Actually, there is no such error in the latest one (1.0.01), in term of source code I mean.

**Comment by Yonaba** [comment]
I just tried with [30log-0.9.1-1](https://raw.githubusercontent.com/Yonaba/30log/30log-0.9.1-1/30log.lua). It just works fine, too.

**Comment by mondwan** [comment]
ahh... I spot the bug. The problematic code located on my mocks.

```
local commandUnit = require 'cli_arch.command_unit'

local ret = commandUnit:new({  -- this error line
    name = 'MockCommandDate'
})

return ret 
```

It throws errors during running test cases.  Since the wrong codes located in the mocks, so I cannot find that codes at first :'(.

Thanks for your time.

**Comment by Yonaba** [comment]
No problem, glad to know you fixed it! :+1:
